/* import IAppointment from "./IAppointments";

const AllAppointment: IAppointment[] = [
  {
    date: "10/03/2024",
    time: "09:00 AM",
    userId: "12345",
    status: "active",
    patientName: "Juan Pérez",
    doctorName: "Dr. González",
    durationMinutes: 60,
    location: "123 Calle Principal",
    notes: "Notas adicionales, si las hay",
  },
  {
    date: "11/03/2024",
    time: "10:00 AM",
    userId: "67890",
    status: "active",
    patientName: "María García",
    doctorName: "Dr. Martínez",
    durationMinutes: 45,
    location: "456 Avenida Secundaria",
    notes: "Notas adicionales",
  },
  {
    date: "12/03/2024",
    time: "11:00 AM",
    userId: "54321",
    status: "canceled",
    patientName: "José Rodríguez",
    doctorName: "Dr. Sánchez",
    durationMinutes: 30,
    location: "789 Boulevard Terciario",
    notes: "Notas de cita cancelada",
  },
  {
    date: "13/03/2024",
    time: "12:00 PM",
    userId: "09876",
    status: "active",
    patientName: "Ana Martínez",
    doctorName: "Dra. López",
    durationMinutes: 75,
    location: "1011 Plaza Cuaternaria",
    notes: "Notas para nueva cita",
  },
  {
    date: "14/03/2024",
    time: "01:00 PM",
    userId: "13579",
    status: "canceled",
    patientName: "Carlos López",
    doctorName: "Dr. García",
    durationMinutes: 90,
    location: "1213 Carretera Quintana",
    notes: "Notas adicionales",
  },
  {
    date: "10/03/2024",
    time: "09:00 AM",
    userId: "12345",
    status: "active",
    patientName: "Juan Pérez",
    doctorName: "Dr. González",
    durationMinutes: 60,
    location: "123 Calle Principal",
    notes: "Notas adicionales, si las hay",
  },
  {
    date: "11/03/2024",
    time: "10:00 AM",
    userId: "67890",
    status: "active",
    patientName: "María García",
    doctorName: "Dr. Martínez",
    durationMinutes: 45,
    location: "456 Avenida Secundaria",
    notes: "Notas adicionales",
  },
  {
    date: "12/03/2024",
    time: "11:00 AM",
    userId: "54321",
    status: "canceled",
    patientName: "José Rodríguez",
    doctorName: "Dr. Sánchez",
    durationMinutes: 30,
    location: "789 Boulevard Terciario",
    notes: "Notas de cita cancelada",
  },
  {
    date: "13/03/2024",
    time: "12:00 PM",
    userId: "09876",
    status: "active",
    patientName: "Ana Martínez",
    doctorName: "Dra. López",
    durationMinutes: 75,
    location: "1011 Plaza Cuaternaria",
    notes: "Notas para nueva cita",
  },
  {
    date: "14/03/2024",
    time: "01:00 PM",
    userId: "13579",
    status: "canceled",
    patientName: "Carlos López",
    doctorName: "Dr. García",
    durationMinutes: 90,
    location: "1213 Carretera Quintana",
    notes: "Notas adicionales",
  },
];

export default AllAppointment;
 */